


--CREATE TABLE mTBLMOVIE --영화 테이블
--(
--	MOVIE_Seq NUMBER PRIMARY KEY, -- 번호
--	name VARCHAR2(300) UNIQUE, -- 제목
--	releaseDate DATE NOT NULL, -- 개봉
--	runningTime VARCHAR2(300) NOT NULL, -- 러닝타임
--	grade NUMBER(3, 1) DEFAULT 0,     -- 평점
--	reOpening DATE NULL,     -- 재개봉
--	cookie VARCHAR2(300) NULL,     -- 쿠키영상
--	cumulAudience NUMBER NOT NULL, -- 누적관객
--	Awards VARCHAR2(300) NULL,     -- 수상내역
--	rating VARCHAR2(300) NOT NULL, -- 등급
--	director VARCHAR2(300) NOT NULL, -- 감독
--	detail VARCHAR2(1500) NOT NULL  -- 내용
--);

CREATE TABLE mTBLMOVIE --영화 테이블
(
	MOVIE_Seq NUMBER PRIMARY KEY, -- 번호
	name VARCHAR2(100) NOT NULL, -- 제목
	releaseDate DATE NOT NULL, -- 개봉
	runningTime VARCHAR2(30) NOT NULL, -- 러닝타임
	grade NUMBER(3, 1) DEFAULT 0,     -- 평점
	reOpening DATE NULL,     -- 재개봉
	cookie VARCHAR2(10) NULL,     -- 쿠키영상
	cumulAudience NUMBER NOT NULL, -- 누적관객
	Awards VARCHAR2(50) NULL,     -- 수상내역
	rating VARCHAR2(100) NOT NULL, -- 등급
	director VARCHAR2(30) NOT NULL, -- 감독
	detail clob NOT NULL  -- 내용
);





CREATE TABLE mTBLGENRE -- 장르
(
	GENRE_Seq NUMBER PRIMARY KEY,
	name VARCHAR2(300) NOT NULL 
);


CREATE TABLE mTBLGENRELIST -- 장르리스트
(
	mgSeq NUMBER PRIMARY KEY,
	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	gSeq NUMBER NOT NULL REFERENCES mTBLGENRE(GENRE_Seq)
);




CREATE TABLE mTBLOTT	-- OTT
(
	OTT_Seq NUMBER PRIMARY KEY,
	name VARCHAR2(300) NOT NULL 
);

CREATE TABLE mTBLOTTLIST -- OTT리스트
(
	moSeq NUMBER PRIMARY KEY,
	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	oSeq NUMBER NOT NULL REFERENCES mTBLOTT(OTT_Seq)
);




CREATE TABLE mTBLCOUNTRY	-- 국가
(
	COUNTRY_Seq NUMBER PRIMARY KEY,
	name VARCHAR2(300) NOT NULL 
);

CREATE TABLE mTBLCOUNTRYLIST -- 국가리스트
(
	mcSeq NUMBER PRIMARY KEY,
	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	cSeq NUMBER NOT NULL REFERENCES mTBLCOUNTRY(COUNTRY_Seq)
);






--CREATE TABLE mTBLSERIES	-- 시리즈
--(
--	SERIES_Seq NUMBER PRIMARY KEY,
--	name VARCHAR2(300) NOT NULL ,
--	releaseDate DATE NULL
--    
--);

CREATE TABLE mTBLSERIES	-- 시리즈
(
	SSEQ NUMBER PRIMARY KEY,
	name clob NOT NULL ,
	RELEASEDATE DATE NULL
);

--CREATE TABLE mTBLSERIESLIST -- 시리즈리스트
--(
--	msSeq NUMBER PRIMARY KEY,
--	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
--	sSeq NUMBER NOT NULL REFERENCES mTBLSERIES(SERIES_Seq)
--);

CREATE TABLE mTBLSERIESLIST -- 시리즈리스트
(
	SEQ NUMBER PRIMARY KEY,
	MSEQ NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	SSEQ NUMBER NOT NULL REFERENCES mTBLSERIES(SSEQ)
);




CREATE TABLE mTBLLINE	-- 명대사
(
	LINE_Seq NUMBER PRIMARY KEY,
	movieLine VARCHAR2(300) NOT NULL 
);

CREATE TABLE mTBLLINELIST -- 명대사리스트
(
	mlSeq NUMBER PRIMARY KEY,
	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	lSeq NUMBER NOT NULL REFERENCES mTBLLINE(LINE_Seq)
);




CREATE TABLE mTBLOST -- OST
(
	OST_Seq NUMBER PRIMARY KEY,
	name VARCHAR2(300) NOT NULL 
);

CREATE TABLE mTBLOSTLIST -- OST리스트
(
	moSeq NUMBER PRIMARY KEY,
	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	oSeq NUMBER NOT NULL REFERENCES mTBLOST(OST_Seq)
);



CREATE TABLE mTBLORIGIN -- 원작
(
	ORIGIN_Seq NUMBER PRIMARY KEY,
	name VARCHAR2(300) NOT NULL ,
	TYPE VARCHAR2(300) NOT NULL,
	author VARCHAR2(300) NOT NULL
);

CREATE TABLE mTBLORIGINLIST -- 원작리스트
(
	moriSeq NUMBER PRIMARY KEY,
	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	originSeq NUMBER NOT NULL REFERENCES mTBLORIGIN(ORIGIN_Seq)
);






CREATE TABLE mTBLCREW -- 제작진
(
	CREW_Seq NUMBER PRIMARY KEY,
	name VARCHAR2(300) NOT NULL 
);
--
--CREATE TABLE mTBLCREWLIST -- 제작진리스트
--(
--	mcSeq NUMBER PRIMARY KEY,
--	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
--	cSeq NUMBER NOT NULL REFERENCES mTBLCREW(CREW_Seq),
--	ROLE VARCHAR2(300) NULL 
--);
CREATE TABLE mTBLCREWLIST -- 제작진리스트
(
   mcSeq NUMBER PRIMARY KEY,
   mSeq NUMBER NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
   cSeq varchar2(300) NOT NULL ,
   ROLE VARCHAR2(300) NULL 
);



CREATE TABLE mTBLPROD -- 영화사
(
	PROD_Seq NUMBER PRIMARY KEY,
	name VARCHAR2(300) NOT NULL 
);

CREATE TABLE mTBLPRODLIST -- 영화사리스트
(
	mpSeq NUMBER PRIMARY KEY,
	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	pSeq NUMBER NOT NULL REFERENCES mTBLPROD(PROD_Seq),
	ROLE VARCHAR2(300) NOT NULL 
);




CREATE TABLE mTBLACTOR -- 배우
(
	ACTOR_Seq NUMBER PRIMARY KEY,
	name VARCHAR2(300) NOT NULL 
);

CREATE TABLE mTBLACTORLIST -- 배우진리스트
(
	maSeq NUMBER PRIMARY KEY,
	mSeq NUMBER NOT NULL REFERENCES mTBLMOVIE(MOVIE_Seq),
	aSeq NUMBER NOT NULL REFERENCES mTBLACTOR(ACTOR_Seq),
	ROLE VARCHAR2(300) NOT NULL,
	casting VARCHAR2(300) NULL 
);



--DROP TABLE mTBLGENRE;
--DROP TABLE mTBLGENRELIST;
--DROP TABLE mTBLOTT;
--DROP TABLE mTBLOTTLIST;
--DROP TABLE mTBLCOUNTRY;
--DROP TABLE mTBLCOUNTRYLIST;
--DROP TABLE mTBLSERIES;
--DROP TABLE mTBLSERIESLIST;
--DROP TABLE mTBLLINE;
--DROP TABLE mTBLLINELIST;
--DROP TABLE mTBLOST;
--DROP TABLE mTBLOSTLIST;
--DROP TABLE mTBLORIGIN;
--DROP TABLE mTBLORIGINLIST;
--DROP TABLE mTBLCREW;
--DROP TABLE mTBLCREWLIST;
--DROP TABLE mTBLPROD;
--DROP TABLE mTBLPRODLIST;
--DROP TABLE mTBLACTOR;
--DROP TABLE mTBLACTORLIST;
--DROP TABLE mTBLMOVIE;


























