--OST
CREATE SEQUENCE OST_Seq;
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'탑건 : 매버릭 (Top Gun: Maverick) (영화 OST)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Avatar: The Way of Water (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'공조2: 인터내셔날');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Doctor Strange in the Multiverse of Madness (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'올빼미 OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Thor: Love and Thunder (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Minions: The Rise Of Gru (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Black Panther: Wakanda Forever (Original Score)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Spider-Man: No Way Home (Original Motion Picture Soundtrack) 영화 <스파이더맨: 노 웨이 홈> OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'영웅');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'브로커');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Fantastic Beasts: The Secrets of Dumbledore (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'인생은 아름다워 OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'정직한 후보 2 OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Sing 2 (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Uncharted (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'오늘 밤, 세계에서 이 사랑이 사라진다 해도 ');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'이상한 나라의 수학자 OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'고백 (영화 ''동감'' X 츄 (이달의 소녀))');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'습관 (Bye Bye) (영화 ''동감'' X meenoi (미노이))');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'개똥벌레 (영화 ''동감'' X 이무진)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'너에게로 가는 길 (영화 ''동감'' X 엔플라잉 (N.Flying))');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'늘 지금처럼 (영화 ''동감'' X VIVIZ (비비지))');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'편지 (영화 ''동감'' X 윤하 (YOUNHA))');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'너를 위해 (영화 ''동감'' X 황치열)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'Morbius (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'늑대사냥 OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'''뽀로로 극장판 드래곤캐슬 대모험'' OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'특송 OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'리멤버 OST');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'The King''s Man (Original Motion Picture Soundtrack)');
INSERT INTO mTBLOST (OST_Seq, name) values ((SELECT nvl(max(OST_Seq), 0) + 1 FROM mTBLOST),'뜨거운 피 OST');
drop SEQUENCE OST_Seq;