CREATE SEQUENCE LINE_Seq;
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values (1,'누가 5야?');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'너 납치된 거야.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'돌아오는 법도 가르쳐야죠.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'우리 가족은 하나야.그것이 강점이자 약점이지.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'물의 길은 시작도 끝도 없다. 물의 길은 모든걸 잇는다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'우리에겐 더 압도적인 승리가 필요하다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'이번 전쟁은 의와 불의의 싸움이다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'다 처먹으려다 전부를 잃는거야'); --
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'아무리 시대가 바껴도 수사는 발로 뛰는거고 수갑은 형사가 채우는거야.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'한 번 길을 잃었다고 해서, 영원히 잃은 건 아니야.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'같은 목표를 위해 잠시 한 배를 탄 것 뿐이야.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'무엇이 보이십니까?');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'학질이요...');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'때로는 눈 감고 사는 게 편할 때도 있습니다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'우리는 세상을 지배하는 것이 아니라 자연에 종속되는 존재이다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'오랜만이네?');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'내 길은 내가 선택하고 싶어.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'가장 작은 자도 무언가를 할 수 있다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'보여줘, 우리가 누구인지');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'나락에 떨어져 본 자만이 위대한 지도자가 될 수 있지');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'할 수 있는데까진 해봐야죠, 끝까지');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'나는 여기 비행기에 탄 사람들이 전부 죽었으면 좋겠어요.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'큰 힘에는 큰 책임이 따르지');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'보고 싶을 때 볼 수 있는게 그거이 통일이다!');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'우는구나, 마침내.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'내가 그렇게 나쁩니까?');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'밥은 먹고 합시다 시간은 기니까.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'꼬레아 우라 꼬레아 우라 꼬레아 우라!');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'우두머리는 죽음을 두려워해야 돼, 그래야 다같이 살 길을 찾으려고 하거든');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'버려진 게 아니라 구해진거야.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'태어나줘서 고마워,');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'위험한 시대에는 위험한 자가 유세하지.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'덕분에 행복하게 잘 살다 갑니다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'지금까지 살고 있으면 사이 좋은 거야.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'땅끝에 오면 끝일 줄 알았는데 끝에 보길도가 있네. 사는 것도 그랬으면 좋겠다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'상황이 그러면 훌륭한 사람도 알 수 없는 게 세상이야.'); ----------
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'우리가 쓰러지면 남은 이들이 못 버팁니다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'만약 그떄로 돌아간대도 같은 선택을 하실 겁니까?');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'긴 실을 더 만들어야 했습니다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'너는.. 끝까지 잡아서 죽인다.'); --
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'도망을 가서 숨는 건 경험상 현명한 결정이 아냐.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'걱정, 두려움 때문에 기회를 놓칠 순 없어, 밑져야 본전이잖아!');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'내 힘은 축복이 아닌 저주이자 분노에서 태어났다!');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'지는사람이 있어야 이기는게 의미가 있지.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'증언은 증거보다 힘이없어요.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'보물은 사라진게아니라 행방을모르는거야');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'니가 다 옳은거같지?');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'둘이 함께 내일의 너를 속이는거야.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'형! 외모가 중요한게 아니잖아');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'정답보다 중요한 건 답을 찾는 과정이다.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'마음 가는 대로 솔직하게,  진실은 언제나!');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'확신에 차있는 사람의 모습은 이런 거구나.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'내가 웃고 있구나');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'한 시간만 정상으로 돌아가면 뭘하고 싶어?');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'인생이 원래 이렇게 힘든 거에요?');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'이 정도면 목숨 걸어야 돼');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'자식이 잘못된 길로 가면 바로 잡아주는게 부모의 도리야');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'용서받을 기회는 아버님이 없애신 거예요.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'죄를 지었으면 벌을 받아 죽음으로써 도망치지 말고..!');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'특권을 타고 났다면 먼저 모범을 보여야 한다. ');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'신사는 그림자 속에 숨지 않지.');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'한번 악당은 평생 악당!');
INSERT INTO mTBLLINE (LINE_Seq, movieLine) values ((SELECT nvl(max(LINE_Seq), 0) + 1 FROm mTBLLINE) ,'싸움은 망설이는 놈이 지는 기다.');
drop SEQUENCE LINE_Seq;