-------------국가---------
CREATE SEQUENCE COUNTRY_Seq;
INSERT INTO mTBLCOUNTRY VALUES (COUNTRY_Seq.nextVal,'한국'); 
INSERT INTO mTBLCOUNTRY VALUES (COUNTRY_Seq.nextVal,'미국'); 
INSERT INTO mTBLCOUNTRY VALUES (COUNTRY_Seq.nextVal,'영국'); 
INSERT INTO mTBLCOUNTRY VALUES (COUNTRY_Seq.nextVal,'일본'); 
drop sequence COUNTRY_Seq;
