CREATE SEQUENCE maSeq;
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 218, '주연', '마석도 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 369, '주연', '강해상 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 720, '주연', '전일만 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 291, '출연', '장이수 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 821, '출연', '오동균 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 807, '출연', '강홍석 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 648, '출연', '김상훈 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 159, '출연', '최춘백 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 290, '출연', '김인숙 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 572, '출연', '박영사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 519, '출연', '장기철 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 126, '출연', '장순철 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 521, '출연', '두익 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 620, '출연', '유종훈 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 526, '출연', '이종두 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 101, '출연', '김기백 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 710, '출연', '최용기 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 259, '출연', '박실장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 733, '출연', '사마귀 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 310, '출연', '은갈치 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 477, '출연', '라꾸 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 6, '출연', '까불이 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 377, '출연', '베트남 형사 트란 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 814, '출연', '애꾸선장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 341, '출연', '식용유 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 39, '출연', '짱구 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 280, '출연', '슈퍼 여대생 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 528, '출연', '슈퍼 주인 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 111, '출연', '여비서 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 823, '출연', '화교 살수1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 575, '출연', '화교 살수2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 719, '출연', '미얀마 살수1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 36, '출연', '미얀마 살수2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 35, '출연', '미얀마 살수3 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 618, '출연', '미얀마 살수4 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 82, '출연', '공항 택시기사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 619, '출연', '외사과 간부 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 637, '출연', '베트남 도박장 건달1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 647, '출연', '금천경찰서장 역 특별출연');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 1, 508, '출연', '휘발유 역 특별출연');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 785, '주연', '매버릭 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 226, '주연', '루스터 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 659, '주연', '페니 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 301, '출연', '아이스맨 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 258, '출연', '혼도 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 691, '출연', '사이클론 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 714, '출연', '월록 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 242, '출연', '피닉스 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 202, '출연', '밥 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 661, '출연', '페이백 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 176, '출연', '팬보이 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 41, '출연', '행맨 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 236, '출연', '프리츠 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 476, '출연', '헤일로 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 40, '출연', '코요태 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 666, '출연', '하버드 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 195, '출연', '예일 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 700, '출연', '사라 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 447, '출연', '케인 해군 소장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 217, '출연', '아멜리아 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 2, 606, '출연', '오마하 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 339, '주연', '제이크 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 672, '주연', '네이티리 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 387, '주연', '키리 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 384, '주연', '쿼리치 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 744, '주연', '로날 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 763, '출연', '토노와리 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 682, '출연', '노엄 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 1, '출연', '모아트 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 450, '출연', '아드모어 장군 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 326, '출연', '스코어스비 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 608, '출연', '가빈 박사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 665, '출연', '네테이엄 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 327, '출연', '로아크 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 607, '출연', '스파이더 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 186, '출연', '로초 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 698, '출연', '파커 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 789, '출연', '투크 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 800, '출연', '아오눙 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 762, '출연', '어린 로아크 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 3, 315, '출연', '츠이레야 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 294, '주연', '이순신 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 319, '주연', '와키자카 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 410, '주연', '어영담 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 373, '주연', '원균 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 89, '주연', '준사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 90, '주연', '가토 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 135, '출연', '정보름 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 775, '출연', '임준영 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 24, '출연', '이억기 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 291, '출연', '나대용 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 686, '출연', '마나베 사마노조 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 515, '출연', '구로다 칸베에 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 299, '출연', '이운룡 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 283, '출연', '와타나베 시치에몬 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 539, '출연', '와키자카 사헤에 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 113, '출연', '정운 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 517, '출연', '송희립 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 43, '출연', '구키 요시타카 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 573, '출연', '황박 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 73, '출연', '이언량 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 45, '출연', '김완 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 367, '출연', '신호 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 411, '출연', '권준 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 558, '출연', '이기남 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 102, '출연', '정담 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 25, '출연', '고바야카와 다카카케 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 307, '출연', '김천손 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 57, '출연', '이영남 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 642, '출연', '이봉수 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 826, '출연', '이광 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 130, '출연', '권율 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 137, '출연', '의병장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 69, '출연', '어영담부장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 23, '출연', '안코쿠지 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 828, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 132, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 281, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 536, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 819, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 28, '출연', '권율부장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 8, '출연', '기생7 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 67, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 735, '출연', '사헤에첩보대7 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 52, '출연', '사헤에첩보대1(사헤에부장) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 66, '출연', '도도 다카도라 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 4, 247, '출연', '초계변씨(이순신 모) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 827, '주연', '림철령 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 501, '주연', '강진태 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 513, '주연', '박민영 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 174, '주연', '잭 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 703, '주연', '장명준 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 600, '출연', '박소연 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 299, '출연', '박상위 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 588, '출연', '김상사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 510, '출연', '김철수 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 265, '출연', '강연아 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 612, '출연', '원형술 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 615, '출연', '김정택 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 580, '출연', '표반장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 340, '출연', '서형사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 550, '출연', '오덕 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 568, '출연', '종구 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 297, '출연', '양복쟁이 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 533, '출연', '선호 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 288, '출연', '조사장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 813, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 723, '출연', '보이스피싱팀원1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 121, '출연', '보이스피싱팀장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 352, '출연', '보이스피싱팀원2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 107, '출연', '세르게이 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 5, 676, '출연', '한광성 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 314, '주연', '닥터 스트레인지 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 453, '주연', '완다 막시모프/스칼렛위치 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 313, '출연', '웡 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 364, '출연', '아메리카 차베즈 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 739, '출연', '모르도 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 196, '출연', '크리스틴 팔머 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 224, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 361, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 446, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 427, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 6, 408, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 566, '주연', '박평호 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 645, '주연', '김정도 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 621, '주연', '방주경 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 822, '주연', '장철성 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 21, '주연', '조유정 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 117, '주연', '안부장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 626, '주연', '양보성 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 593, '출연', '운반자 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 622, '출연', '천보산 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 649, '출연', '표동호 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 376, '출연', '강부장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 5, '출연', '정도 아내 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 588, '출연', '보안사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 631, '출연', '김순식 장군 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 370, '출연', '남한 태동령 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 792, '출연', 'CIA 지부장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 129, '출연', '신기철 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 464, '출연', '강기자 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 278, '출연', '목성사 사내2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 725, '출연', '목성사 사내4 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 126, '출연', '국내팀 요원1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 643, '출연', '강령군 북한군10 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 774, '출연', '강령군 북한군12 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 289, '출연', '동경지부 요원6 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 62, '출연', '강령군 북한군1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 98, '출연', '강령군 북한군2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 287, '출연', '목성사 소각 남직원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 731, '출연', '해외팀 요원2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 34, '출연', '정도 둘째 아들 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 675, '출연', 'CIA 요원1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 271, '출연', '동경지부요원1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 683, '출연', '동경지부요원2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 53, '출연', '동경지부요원3 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 694, '출연', '동경지부요원4 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 835, '출연', '리중좌 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 544, '출연', '조원식 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 7, 497, '출연', '최대표 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 208, '주연', '천경수 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 501, '주연', '인조 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 724, '출연', '이형익 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 679, '출연', '최대감 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 261, '출연', '만식 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 92, '출연', '소현세자 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 412, '출연', '소용조씨 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 684, '출연', '강빈 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 572, '출연', '석철 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 103, '출연', '서상궁 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 630, '출연', '내금위장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 411, '출연', '청사신 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 127, '출연', '최상궁 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 204, '출연', '선배의원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 97, '출연', '대신1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 82, '출연', '침맞는내관 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 23, '출연', '경수인솔별감1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 169, '출연', '사내1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 414, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 472, '출연', '강빈(세자)궁녀1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 8, 15, '출연', '선생 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 757, '주연', '오웬 그래디 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 323, '주연', '클레어 디어링 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 199, '출연', '엘리 새틀러 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 337, '출연', '앨런 그랜트 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 668, '출연', '이안 말콤 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 187, '출연', '케일라 와츠 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 221, '출연', '램지 콜 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 535, '출연', '에이지 록우드 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 743, '출연', '루이스 독슨 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 328, '출연', '헨리 우 박사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 463, '출연', '베리 셈벤 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 609, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 175, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 380, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 190, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 760, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 795, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 9, 422, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 391, '주연', '소녀 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 279, '주연', '경희 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 343, '주연', '조현 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 701, '주연', '용두 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 357, '주연', '대길 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 677, '주연', '백 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 708, '출연', '변박 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 610, '출연', '톰 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 318, '출연', '미영 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 715, '출연', '토우 여자1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 344, '출연', '토우 여자2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 625, '출연', '토우 여자2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 51, '출연', '토우 미소년 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 604, '출연', '미영친구 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 641, '출연', '흉터소녀 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 394, '출연', '여자아이 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 241, '출연', '산월패션 남직원1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 696, '출연', '조현 팀원1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 723, '출연', '용두패2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 477, '출연', '사내1 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 302, '출연', '토우 소녀 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 504, '출연', '장 수하2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 652, '출연', '용두패7 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 735, '출연', '사내3 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 395, '출연', '양주임 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 569, '출연', '장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 54, '출연', '자윤 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 10, 445, '출연', '마트 행인 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 758, '주연', '토르 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 154, '주연', '마이티 토르 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 759, '주연', '고르 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 778, '주연', '킹 발키리 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 768, '주연', '코르그 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 194, '출연', '제우스 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 663, '출연', '시프 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 757, '출연', '피터 퀼/ 스타로드 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 181, '출연', '드랙스 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 740, '출연', '네뷸라 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 794, '출연', '맨티스 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 378, '출연', '크래글린 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 331, '출연', '그루트 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 324, '출연', '로켓 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 316, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 382, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 11, 182, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 383, '주연', '그루 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 766, '주연', '벨 바텀 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 438, '주연', '마스터 초우 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 798, '주연', '밥/케빈/스튜어트/미니언즈 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 201, '주연', '넌척 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 597, '주연', '장 클로드 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 695, '출연', '말레나 그루 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 185, '출연', '스벤저스 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 178, '출연', '스트롱홀드 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 421, '출연', '와일드 너클스 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 193, '출연', '네파리오 박사 (목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 12, 211, '출연', '(목소리) 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 197, '주연', '슈리 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 203, '주연', '나키아 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 171, '주연', '오코예 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 486, '출연', '음바쿠 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 413, '출연', '라몬다 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 776, '출연', '네이머 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 235, '출연', '에버렛 로스 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 184, '출연', '손리리 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 796, '출연', '아요 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 255, '출연', '아네카 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 424, '출연', '아투마 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 222, '출연', '나모라 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 561, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 177, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 596, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 365, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 746, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 13, 788, '출연', 'null');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 374, '주연', '인호 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 534, '주연', '재혁 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 613, '주연', '숙희 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 53, '주연', '현수 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 590, '주연', '진석 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 94, '주연', '희진 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 295, '주연', '태수 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 478, '출연', '혜윤 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 826, '출연', '박윤철 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 247, '출연', '한박사 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 351, '출연', '임태은 승무원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 37, '출연', '구민정 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 80, '출연', '박수민 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 46, '출연', '미량 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 593, '출연', '원동연 기장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 554, '출연', '박시영 승무원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 588, '출연', '종수 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 537, '출연', '장영석 기장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 129, '출연', '윤석 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 158, '출연', '청와대 안보실장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 651, '출연', '석필호 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 142, '출연', '백장관 보건 복지부 장관 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 582, '출연', '오성훈 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 548, '출연', '혜윤친구들 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 619, '출연', '건설사 출장 직원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 699, '출연', '취업기념 여행자 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 578, '출연', '백장관 보좌관 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 278, '출연', '도쿄 관제소 팀장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 348, '출연', '도쿄 관제소 팀원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 93, '출연', '윤석 가족 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 470, '출연', '승무원 동생 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 243, '출연', '외국인 커플 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 507, '출연', '취업기념 여행자 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 131, '출연', '시위대 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 836, '출연', '골프회원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 320, '출연', '골프회원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 14, '출연', 'NSC 앞 기자 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 803, '출연', '브리콤 경비 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 62, '출연', '관제탑 군인 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 125, '출연', '관제팀장2 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 733, '출연', '관제팀원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 12, '출연', '대응팀 질본위 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 512, '출연', '골프회원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 529, '출연', '여고생 가족 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 349, '출연', '다이빙 동호회 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 467, '출연', '골프회원 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 702, '출연', '혜윤친구들 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 321, '출연', '비행감시팀장 역');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 475, '출연', '뉴스 앵커 역특별출연');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 14, 564, '출연', '뉴스 아나운서 역특별출연');
INSERT INTO mTBLACTORLIST values((SELECT nvl(max(maSeq), 0) + 1 FROM mTBLACTORLIST), 15, 787, '주연', '피터 파커/스파이더맨 역');
DROP SEQUENCE maSeq;