CREATE SEQUENCE PROD_Seq;
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '빅펀치픽쳐스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜비에이엔터테인먼트');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜홍필름');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜에이비오엔터테인먼트');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '롯데컬처웍스㈜롯데엔터테인먼트');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '월트 디즈니 컴퍼니 코리아');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜빅스톤픽쳐스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜JK필름');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), 'CJ ENM');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '영화사 창건');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '아티스트스튜디오㈜');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜사나이픽처스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '플러스엠 엔터테인먼트');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜씨제스엔터테인먼트');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜영화사 담담');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜NEW');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '유니버설 픽쳐스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜영화사 금월');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '일루미네이션 엔터테인먼트');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜매그넘나인');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜쇼박스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '씨네주(유) CINE ZOO');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '소니 픽쳐스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), 'TPS COMPANY');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '싸이더스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '씨나몬㈜홈초이스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜모호필름');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜케이퍼필름');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '에이콤');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '어뉴');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '오스카10스튜디오');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜영화사 집');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '워너브러더스 코리아㈜');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '더 램프㈜');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '이스트드림 시노펙스㈜');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜기억속의 매미');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜마인드마크');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜수필름');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '씨앗필름');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜마인드마크');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '리얼라이즈 픽쳐스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '리양필름');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜에이스메이커무비웍스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '홀리가든');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '바이포엠스튜디오');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜미디어캐슬');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜대교');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '대원미디어㈜');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜포켓몬 코리아');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '조이래빗');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '고고스튜디오');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), 'CJ CGV');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '콘텐츠지');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), 'TCO㈜더콘텐츠온');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜영화사 채움');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), 'OCON STUDIOS');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '엠픽처스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), 'Library Pictures International');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜더타워픽쳐스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '폭스 인터내셔널 프러덕션 (코리아)');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜영화사 월광');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '드림웍스 (DreamWorks SKG)');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜고래픽처스');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜스튜디오 디에이치엘 (Studio dhL inc.)');
INSERT INTO mtblprod VALUES ((SELECT nvl(max(PROD_Seq), 0) + 1 FROM mtblprod), '㈜키다리스튜디오');
drop SEQUENCE PROD_Seq;