CREATE SEQUENCE mcSeq;
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '마동석, 김홍백, 장원석, 유영채', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '강윤성, 마동석, 강윤성', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '김민성', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '이상용, 마동석, 이영종', '각색');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '주성림', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '최종하', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '김태성, 정상우', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '김선민', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '박용기', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '방길성, 김순근, 남성주, 남지수', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '박대훈, 피대성, 엄세용, 김병민, 전민규', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '허명행, 윤성민', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 1, '아이락김', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '제리 브룩하이머, 톰 크루즈, 데이빗 엘리슨, 크리스토퍼 맥쿼리 ', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '데이나 골드버그, 돈 그레인저, 토미 하퍼, 채드 오먼, 마이크 스텐슨', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '짐 캐쉬, 잭 엡스 주니어', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '에렌 크루거, 에릭 워렌 싱어, 크리스토퍼 맥쿼리, 피터 크레이그, 저스틴 막스', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '클라우디오 미란다', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '론 발페, 해럴드 팔터메이어, 레이디 가가, 한스 짐머', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '에디 헤밀턴', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '제레미 힌들, 클린트 월레스, 앤드류 맥카시, 잔 파스케일', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '말렌 스튜어트', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 2, '데니스 채미언', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '제임스 카메론, 존 랜도', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '리처드 베인햄, 피터 M. 토비얀센, 데이빗 발데스', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '제임스 카메론, 릭 자파, 아만다 실버', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '러셀 카펜터', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '사이먼 프랜글렌', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '데이빗 브레너, 제임스 카메론, 존 르포아, 스티븐 E. 리브킨', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '딜런 콜, 벤 프록터, 루크 프리본, 킴 싱클레어', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '조 레터리, 리처드 베인햄', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 3, '매거리 심킨', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '김한민, 김주경', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '김한민', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '김한민', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '김태성', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '김경석', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '김태성', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '이강희, 안현건', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '김석원', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '조화성', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '권유진, 임승희', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 4, '정성진, 정도안, 임종혁', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '윤제균, 길영민, 이선영, 이석훈, 홍아름, 주승환, 최준호', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '임성순', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '이석훈, 윤제균', '각색');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '홍재식', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '김재근', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '황상준', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '남나역', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '박현수', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '한명환', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '이태훈, 이진형, 장석호', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '김은숙, 이진영', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '홍장표, 윤황직, 김세희', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '김태강, 최동헌', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 5, '백경윤', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 6, '케빈 파이기', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 6, '스콧 데릭슨', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 6, '스티브 딧코, 스탠 리', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 6, '마이클 월드론', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 6, '존 매티슨', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 6, '대니 엘프만', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 6, '찰스 우드, 존 부시', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 6, '새러 핀', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '한재덕, 이정재, 박민정, 조재상', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '이정재, 조승희', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '백경윤, 오세혁, 이영종', '각색');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '이모개, 이종우, 이의태', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '이성환', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '조영욱', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '김상범', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '정군', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '김창섭', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '박일현, 박준용, 박승현', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '조상경, 최윤선, 손은주', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '정도안, 윤형태, 황효균, 곽태용, 장익제, 김태의', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '허명행, 김선웅', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 7, '이광기, 조성구', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 8, '현규리, 안태진', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 8, '김태경', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 8, '홍승철', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 8, '이하준', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 9, '패트릭 크롤리, 프랭크 마샬', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 9, '알렉산드라 퍼거슨-더비셔, 스티븐 스필버그, 콜린 트레보로우', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 9, '마이클 크라이튼', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 9, '에밀리 카마이클, 듀렉 코놀리, 콜린 트레보로우', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 9, '존 슈워츠만', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 9, '마크 생어', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 9, '케빈 젠킨스', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 9, '니나 골드', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '신민경', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '박훈정', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '김영호', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '조용준', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '모그', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '장래원, 장래원', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '김신용', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '김창섭', '음햑');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '조화성, 최현석, 오진석', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '조상경, 김현정', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '황효균, 곽태용, 박경수, 이동호, 조용석, 장민재', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '김정민', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 10, '줄리', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '케빈 파이기, 브래드 윈더바움', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '빅토리아 알론소, 브라이언 채펙 , 루이스 디에스포지토, 토드 할로웰, 크리스 헴스워스', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '스탠 리, 제이슨 에런', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '타이카 와이티티, 제니퍼 케이틴 로빈슨', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '배리 바즈 이도이네', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '마이클 지아치노, 나미 멜루마드', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '피터 S. 엘리엇, 팀 로슈, 매튜 슈미트, 제니퍼 베치아렐로', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '니겔 펠프스, 찰리 레바이, 케이티 샤록', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '메이스 C.루베오', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 11, '새러 핀', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 12, '자넷 힐리, 크리스토퍼 멜레단드리, 크리스 리노드', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 12, '라티차 오우아오우', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 12, '친코 폴', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 12, '매튜 포겔, 브라이언 린치', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 12, '클레어 도지슨', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '케빈 파이기, 네이트 무어', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '빅토리아 알론소, 루이스 디에스포지토, 배리 H. 월드먼', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '라이언 쿠글러, 조 로버트 콜', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '오툼 듀랄드', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '루드비히 고란손', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '켈리 딕슨, 제니퍼 레임, 마이클 P. 쇼버', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '한나 비츨러, 브래드 리커, 리사 K. 세션스', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '루스 E. 카터, 카밀 프렌드', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 13, '새러핀', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '김대승, 김요환, 한재훈', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '한재림', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '이모개, 박종철', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '이성환', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '이병우', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '한재림, 김우현, 이강일', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '이목원, 박재완, 채경화', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '채경화, 김서영', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 14, '류영재, 황효균, 홍정호', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '케빈 파이기, 에이미 파스칼', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '빅토리아 알론소,  아비 아라드, 루이스 디에스포지토, 레이첼 오코너r, 조앤 페리타노, 매튜 톨마치', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '스탠 리, 스티브 딧코', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '크리스 맥케나, 에릭 소머즈', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '마우로 피오레', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '마이클 지아치노', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '리 폴섬 보이드, 제프리 포드', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '대런 길포드, 데이비드 스콧, 로즈메리 브란데버그, 엠마누엘 호슬리, 산자 밀코빅 헤이스', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 15, '새러 핀, 크리스 자라고자', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 16, '박규태', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '박찬욱, 고대석', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '정서경, 박찬욱', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '김지용', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '신상열', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '조영욱', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '김상범', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '정군', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '김석원', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '류성희', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '곽정애, 송종희', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '이전형', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 17, '이선영', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '최동훈, 김성민', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '안수현', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '최동훈', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '김태경', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '홍승철', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '장영규', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '신민경', '편집 ');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '은희수', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '최태영', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '류성희, 이하준', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '조상경, 김현정, 류현민', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '제갈숭', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 18, '이광기, 이가람', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 19, '조상윤', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 19, '황상준', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 20, '천성일', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 20, '권유진, 이혜란', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 20, '강종익, 서병철', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 20, '심상용', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '이유진, 송대찬', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '고레에다 히로카즈', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '홍경포', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '박정우', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '정재일', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '고레에다 히로카즈', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '은희수, 최태영', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '이목원', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '최세연, 김서영', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '백상훈', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 21, '이선영, 허진석', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 22, '데이비드 헤이만', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 22, '조앤 K. 롤링', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 22, '조앤 K. 롤링', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '박은경', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '남성호', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '박은경', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '배세영', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '백윤석', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '이선용', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '김창호', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '김준석', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '양진모', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '이순성', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '최태영', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '손민정', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '김영복', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '최세연', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '강동률', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '황현규', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '김정자', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '박의동', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '배상민', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '신진', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '박대훈', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '도광일', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '송민석', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 23, '이병윤', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '딜런 클락, 매트 리브스', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '사이먼 엠마누엘, 윌터 하마다, 마이클 E. 어슬란', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '피터 크레이그, 매트 리브스', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '그레이그 프레이저', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '마이클 지아치노', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '윌리엄 호이, 타일러 넬슨', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '제임스 킨런드, 그랜트 암스트롱, 탄자 데쉬다', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '나오미 돈', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 24, '루시 베반, 신디 톨랜', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 25, '황인호, 이진훈', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '김홍백, 민진수, 김창희, 정혜영, 박재성', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '박하나', '각복');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '허성혜, 장유정', '각색');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '유일승', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '이준일', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '이재진', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '신민경', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '임동석', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '공태원', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '기혜인, 김시용, 최홍섭', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '김유선, 박민희', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '홍장표', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '임왕섭', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 26, '강숙', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 27, '가스 제닝스', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 28, '우스이 요시토', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 28, '우에노 키미코', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 29, '보 플린, 대니 가르시아, 히람 가르시아', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 29, '월터 하마다, 드웨인 존슨, 에릭 맥로드, 스콧 셸던', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 29, 'C.C. 벡, 오토 바인더', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 29, '로리 헤인즈, 소라브 노쉬르바니, 애덤 스티키엘', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 29, '로렌스 쉐어', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 29, '존 리', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '이진희, 박준호', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '변성현, 김민수', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '조형래', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '이길규', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '김홍집, 이진희', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '김상범', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '박종근', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '박용기', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '한아름, 김윤석, 송석기', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '조희란, 손은주', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 30, '김대준, 박철용', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '원동연, 김지홍', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '원동연', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '윤종석', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '남다정', '각색');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '김성진', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '신경만', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '모그', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '허선미, 조한울', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '조우진', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '이승엽', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '윤나라, 신보라, 우제형', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '조상경, 조태희', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '이용섭, 하승남', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '모상범, 이병진', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 31, '줄리', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '아리 아라드, 아비 아라드, 크리스토퍼 피서, 알렉스 가트너, 헤닝 몰펜터, 찰스 로빈, 찰리 워브큰', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '데이빗 버나드, 로버트 J. 도어만, 루벤 플레셔, 톰 홀랜드, 매트 할러웨이, 아트 마르쿰, 아사드 키질바쉬, 닐 드럭먼, 카터 스완, 에반 웰스', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '에이미 헤닝', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '레이프 저드킨스, 아트 마르쿰, 매트 할러웨이', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '정정훈', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '라민 드자와디', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '크리스 레번존, 리처드 피어슨', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '쉐퍼드 프랭켈, 데이빗 잉그럼', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 32, '프리실라 존, 올라 맥스웰, 존 팹사이데러', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '배영익', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '강국현', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '김효성', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '장영규', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '남나영', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '한철희', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '이승엽', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '채경선, 진훈', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '김경미, 이은주', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '윤대원, 황효균, 곽태용', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 33, '최봉록', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '마츠오카 히로야스, 카와다 타카히로', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '하루나 케이, 우스이 히사시', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '이치조 미사키', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '츠키카와 쇼, 마츠모토 하나', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '야나기다 히로오', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '미야오 코지', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '카메다 세이지', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '호가키 준노스케', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 34, '마츠나가 케이코, 니시오 토모미', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 35, '오타 케이지, 마츠오카 히로야스', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 35, '아쿠타미 게게', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 35, '세코 히로시', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 35, '츠츠미 히로아키, 테루이 요시마사, 오케하자마 아리사', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 35, '야나기 케이스케', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 35, '아즈마 준이치', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 35, '히라마츠 타다시', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 36, '마동석', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 36, '마동석', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 36, '신연식, 임진순', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 37, '요시카와 초지, 후카자와 미키히코, 오카모토준야, 쿠보 마사카즈, 이토 켄지로, 모리 타케모토', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 37, '타지리 사토시', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 37, '소노다 히데키', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 37, '미마 마사후미', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 37, '모리 카즈아키, 사토 카즈미', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 38, '이용재', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 38, '김선민', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 39, '아오야마 고쇼', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 39, '오오쿠라 타카히로', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 39, '칸노 유고', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 39, '스도 마사토모', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 40, '서은영', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 40, '강숙', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 41, '아비 아라드, 루카스 포스터, 매튜 톨마치', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 41, '자레드 레토, 루이스 로스너, 엠마 루드브룩', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 41, '길 케인, 로이 토마스', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 41, '맷 사자마, 벅 샤프리스', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 41, '올리버 우드', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 41, '존 에크스트랜드', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 41, '스테파니아 셀라', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '구성목, 김홍선, 김상윤, 손정현', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '김홍선, 구성목', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '김홍선, 조수빈', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '윤주환', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '전병윤', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '김준성, 조란', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '신민경, 이가람', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '서지훈', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '이승엽', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '이정우, 전재욱, 오유진, 남성주', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '곽정애, 김진숙', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '윤황직, 홍장표', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 42, '유상섭, 이광기', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 43, '김일호, 우지희, 김현호', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 43, '강승훈, 김창원, 정은경', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 43, '김정아, 박덕수', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 43, '종일오, 김세광, 정애진', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '주승환, 김성훈', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '박대민, 김봉서, 박동희', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '김재근', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '황상준', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '김선민', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '안성일', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '한명환', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '이태훈, 장석호', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '윤황직, 김세희, 홍장표', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '최성겸, 최동헌', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '조상경, 장윤정', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 44, '이진형', '기타');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 45, '진일규', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 45, '김경미, 유영아', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 45, '이창재', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 45, '윤종한', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 45, '김태성, 최정인', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 45, '신민경', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 45, '이상준', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 45, '손은주, 조희란', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '이안 쿠퍼, 조던 필', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '로버트 그라프, 윈 로젠펠드', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '조던 필', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '호이트 반 호이테마', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '마이클 에이벨스', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '니콜라스 몬수어', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '루스 드 종, 진 서데나', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '알렉스 보베어드, 린다 빌라로보스, 제니퍼 자이드', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 46, '카르멘 쿠바', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '국수란, 윤종빈, 문용찬', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '윤종빈', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '이일형, 윤종빈', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '유억', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '배일혁', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '황상준', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '김상범', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '윤성기', '동시녹음');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '김창섭', '음향');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '정은영, 유청, 박준용', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '이희은, 황효균, 곽태용, 정도안, 조경규, 김대준', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '허명행, 권지훈', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 47, '최의영, 박선', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '아담 볼링, 데이빗 레이드, 매튜 본', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '랄프 파인즈, 데이브 기본스, 스티븐 막스, 마크 밀러, 클라우디아 쉬퍼', '기획');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '마크 밀러, 데이브 기본스', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '매튜 본, 칼 가이두섹', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '벤 데이비스', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '도미닉 루이스, 매튜 마르게슨', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '제이슨 발랜타인, 로버트 홀', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '대런 길포드, 더그 J. 미어딩크, 도미닉 카폰', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '미셀 클랩튼', '의상/분장');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 48, '렉 포어스코트-에저튼', '캐스팅');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 49, '에탄 코헨, 아론 블라비', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 49, '아론 블라비', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 49, '에탄 코헨, 힐러리 윈스턴', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '김주경', '제작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '서규석', '조감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '김언수', '원작');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '천명관', '각본');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '강국현', '촬영');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '김효성', '조명');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '윤일상', '음악');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '김창주', '편집');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '이재성', '미술');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '이상민', '특수효과');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '이상하', '무술감독');
INSERT INTO mTBLCREWLIST VALUES (mcSeq.nextval, 50, '최의영, 김현정', '의상/분장');
DROP SEQUENCE mcSeq;