CREATE SEQUENCE CREW_Seq;
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마동석, 김홍백, 장원석, 유영채');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '강윤성, 마동석, 강윤성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김민성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이상용, 마동석, 이영종');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '주성림');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최종하');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김태성, 정상우');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김선민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박용기');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '방길성, 김순근, 남성주, 남지수');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박대훈, 피대성, 엄세용, 김병민, 전민규');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '허명행, 윤성민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '아이락김');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '제리 브룩하이머, 톰 크루즈, 데이빗 엘리슨, 크리스토퍼 맥쿼리 ');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '데이나 골드버그, 돈 그레인저, 토미 하퍼, 채드 오먼, 마이크 스텐슨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '짐 캐쉬, 잭 엡스 주니어');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '에렌 크루거, 에릭 워렌 싱어, 크리스토퍼 맥쿼리, 피터 크레이그, 저스틴 막스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '클라우디오 미란다');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '론 발페, 해럴드 팔터메이어, 레이디 가가, 한스 짐머');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '에디 헤밀턴');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '제레미 힌들, 클린트 월레스, 앤드류 맥카시, 잔 파스케일');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '말렌 스튜어트');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '데니스 채미언');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '제임스 카메론, 존 랜도');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '리처드 베인햄, 피터 M. 토비얀센, 데이빗 발데스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '제임스 카메론, 릭 자파, 아만다 실버');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '러셀 카펜터');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '사이먼 프랜글렌');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '데이빗 브레너, 제임스 카메론, 존 르포아, 스티븐 E. 리브킨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '딜런 콜, 벤 프록터, 루크 프리본, 킴 싱클레어');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조 레터리, 리처드 베인햄');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '매거리 심킨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김한민, 김주경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김한민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김한민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김태성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김경석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김태성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이강희, 안현건');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김석원');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조화성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '권유진, 임승희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '정성진, 정도안, 임종혁');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤제균, 길영민, 이선영, 이석훈, 홍아름, 주승환, 최준호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '임성순');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이석훈, 윤제균');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '홍재식');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김재근');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '황상준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '남나역');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박현수');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '한명환');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이태훈, 이진형, 장석호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김은숙, 이진영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '홍장표, 윤황직, 김세희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김태강, 최동헌');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '백경윤');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '케빈 파이기');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '스콧 데릭슨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '스티브 딧코, 스탠 리');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마이클 월드론');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '존 매티슨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '대니 엘프만');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '찰스 우드, 존 부시');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '새러 핀');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '한재덕, 이정재, 박민정, 조재상');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이정재, 조승희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '백경윤, 오세혁, 이영종');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이모개, 이종우, 이의태');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이성환');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조영욱');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김상범');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '정군');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김창섭');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박일현, 박준용, 박승현');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조상경, 최윤선, 손은주');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '정도안, 윤형태, 황효균, 곽태용, 장익제, 김태의');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '허명행, 김선웅');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이광기, 조성구');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '현규리, 안태진');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김태경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '홍승철');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이하준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '패트릭 크롤리, 프랭크 마샬');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '알렉산드라 퍼거슨-더비셔, 스티븐 스필버그, 콜린 트레보로우');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마이클 크라이튼');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '에밀리 카마이클, 듀렉 코놀리, 콜린 트레보로우');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '존 슈워츠만');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마크 생어');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '케빈 젠킨스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '니나 골드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신민경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박훈정');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김영호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조용준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '모그');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '장래원, 장래원');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김신용');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김창섭');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조화성, 최현석, 오진석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조상경, 김현정');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '황효균, 곽태용, 박경수, 이동호, 조용석, 장민재');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김정민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '줄리');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '케빈 파이기, 브래드 윈더바움');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '빅토리아 알론소, 브라이언 채펙 , 루이스 디에스포지토, 토드 할로웰, 크리스 헴스워스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '스탠 리, 제이슨 에런');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '타이카 와이티티, 제니퍼 케이틴 로빈슨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '배리 바즈 이도이네');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마이클 지아치노, 나미 멜루마드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '피터 S. 엘리엇, 팀 로슈, 매튜 슈미트, 제니퍼 베치아렐로');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '니겔 펠프스, 찰리 레바이, 케이티 샤록');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '메이스 C.루베오');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '새러 핀');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '자넷 힐리, 크리스토퍼 멜레단드리, 크리스 리노드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '라티차 오우아오우');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '친코 폴');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '매튜 포겔, 브라이언 린치');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '클레어 도지슨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '케빈 파이기, 네이트 무어');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '빅토리아 알론소, 루이스 디에스포지토, 배리 H. 월드먼');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '라이언 쿠글러, 조 로버트 콜');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '오툼 듀랄드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '루드비히 고란손');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '켈리 딕슨, 제니퍼 레임, 마이클 P. 쇼버');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '한나 비츨러, 브래드 리커, 리사 K. 세션스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '루스 E. 카터, 카밀 프렌드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '새러핀');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김대승, 김요환, 한재훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '한재림');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이모개, 박종철');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이성환');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이병우');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '한재림, 김우현, 이강일');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이목원, 박재완, 채경화');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '채경화, 김서영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '류영재, 황효균, 홍정호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '케빈 파이기, 에이미 파스칼');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '빅토리아 알론소,  아비 아라드, 루이스 디에스포지토, 레이첼 오코너r, 조앤 페리타노, 매튜 톨마치');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '스탠 리, 스티브 딧코');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '크리스 맥케나, 에릭 소머즈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마우로 피오레');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마이클 지아치노');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '리 폴섬 보이드, 제프리 포드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '대런 길포드, 데이비드 스콧, 로즈메리 브란데버그, 엠마누엘 호슬리, 산자 밀코빅 헤이스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '새러 핀, 크리스 자라고자');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박규태');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박찬욱, 고대석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '정서경, 박찬욱');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김지용');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신상열');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조영욱');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김상범');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '정군');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김석원');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '류성희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '곽정애, 송종희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이전형');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이선영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최동훈, 김성민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '안수현');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최동훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김태경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '홍승철');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '장영규');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신민경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '은희수');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최태영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '류성희, 이하준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조상경, 김현정, 류현민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '제갈숭');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이광기, 이가람');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조상윤');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '황상준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '천성일');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '권유진, 이혜란');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '강종익, 서병철');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '심상용');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이유진, 송대찬');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '고레에다 히로카즈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '홍경포');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박정우');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '정재일');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '고레에다 히로카즈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '은희수, 최태영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이목원');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최세연, 김서영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '백상훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이선영, 허진석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '데이비드 헤이만');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조앤 K. 롤링');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조앤 K. 롤링');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박은경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '남성호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박은경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '배세영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '백윤석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이선용');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김창호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김준석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '양진모');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이순성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최태영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '손민정');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김영복');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최세연');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '강동률');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '황현규');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김정자');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박의동');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '배상민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신진');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박대훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '도광일');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '송민석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이병윤');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '딜런 클락, 매트 리브스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '사이먼 엠마누엘, 윌터 하마다, 마이클 E. 어슬란');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '피터 크레이그, 매트 리브스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '그레이그 프레이저');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마이클 지아치노');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윌리엄 호이, 타일러 넬슨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '제임스 킨런드, 그랜트 암스트롱, 탄자 데쉬다');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '나오미 돈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '루시 베반, 신디 톨랜');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '황인호, 이진훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김홍백, 민진수, 김창희, 정혜영, 박재성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박하나');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '허성혜, 장유정');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '유일승');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이준일');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이재진');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신민경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '임동석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '공태원');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '기혜인, 김시용, 최홍섭');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김유선, 박민희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '홍장표');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '임왕섭');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '강숙');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '가스 제닝스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '우스이 요시토');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '우에노 키미코');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '보 플린, 대니 가르시아, 히람 가르시아');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '월터 하마다, 드웨인 존슨, 에릭 맥로드, 스콧 셸던');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, 'C.C. 벡, 오토 바인더');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '로리 헤인즈, 소라브 노쉬르바니, 애덤 스티키엘');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '로렌스 쉐어');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '존 리');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이진희, 박준호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '변성현, 김민수');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조형래');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이길규');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김홍집, 이진희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김상범');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박종근');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박용기');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '한아름, 김윤석, 송석기');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조희란, 손은주');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김대준, 박철용');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '원동연, 김지홍');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '원동연');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤종석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '남다정');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김성진');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신경만');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '모그');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '허선미, 조한울');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조우진');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이승엽');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤나라, 신보라, 우제형');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조상경, 조태희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이용섭, 하승남');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '모상범, 이병진');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '줄리');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '아리 아라드, 아비 아라드, 크리스토퍼 피서, 알렉스 가트너, 헤닝 몰펜터, 찰스 로빈, 찰리 워브큰');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '데이빗 버나드, 로버트 J. 도어만, 루벤 플레셔, 톰 홀랜드, 매트 할러웨이, 아트 마르쿰, 아사드 키질바쉬, 닐 드럭먼, 카터 스완, 에반 웰스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '에이미 헤닝');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '레이프 저드킨스, 아트 마르쿰, 매트 할러웨이');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '정정훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '라민 드자와디');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '크리스 레번존, 리처드 피어슨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '쉐퍼드 프랭켈, 데이빗 잉그럼');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '프리실라 존, 올라 맥스웰, 존 팹사이데러');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '배영익');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '강국현');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김효성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '장영규');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '남나영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '한철희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이승엽');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '채경선, 진훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김경미, 이은주');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤대원, 황효균, 곽태용');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최봉록');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마츠오카 히로야스, 카와다 타카히로');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '하루나 케이, 우스이 히사시');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이치조 미사키');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '츠키카와 쇼, 마츠모토 하나');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '야나기다 히로오');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '미야오 코지');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '카메다 세이지');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '호가키 준노스케');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마츠나가 케이코, 니시오 토모미');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '오타 케이지, 마츠오카 히로야스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '아쿠타미 게게');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '세코 히로시');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '츠츠미 히로아키, 테루이 요시마사, 오케하자마 아리사');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '야나기 케이스케');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '아즈마 준이치');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '히라마츠 타다시');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마동석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마동석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신연식, 임진순');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '요시카와 초지, 후카자와 미키히코, 오카모토준야, 쿠보 마사카즈, 이토 켄지로, 모리 타케모토');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '타지리 사토시');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '소노다 히데키');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '미마 마사후미');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '모리 카즈아키, 사토 카즈미');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이용재');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김선민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '아오야마 고쇼');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '오오쿠라 타카히로');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '칸노 유고');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '스도 마사토모');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '서은영');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '강숙');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '아비 아라드, 루카스 포스터, 매튜 톨마치');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '자레드 레토, 루이스 로스너, 엠마 루드브룩');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '길 케인, 로이 토마스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '맷 사자마, 벅 샤프리스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '올리버 우드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '존 에크스트랜드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '스테파니아 셀라');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '구성목, 김홍선, 김상윤, 손정현');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김홍선, 구성목');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김홍선, 조수빈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤주환');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '전병윤');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김준성, 조란');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신민경, 이가람');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '서지훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이승엽');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이정우, 전재욱, 오유진, 남성주');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '곽정애, 김진숙');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤황직, 홍장표');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '유상섭, 이광기');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김일호, 우지희, 김현호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '강승훈, 김창원, 정은경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김정아, 박덕수');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '종일오, 김세광, 정애진');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '주승환, 김성훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '박대민, 김봉서, 박동희');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김재근');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '황상준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김선민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '안성일');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '한명환');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이태훈, 장석호');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤황직, 김세희, 홍장표');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최성겸, 최동헌');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조상경, 장윤정');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이진형');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '진일규');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김경미, 유영아');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이창재');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤종한');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김태성, 최정인');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '신민경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이상준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '손은주, 조희란');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이안 쿠퍼, 조던 필');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '로버트 그라프, 윈 로젠펠드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '조던 필');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '호이트 반 호이테마');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마이클 에이벨스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '니콜라스 몬수어');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '루스 드 종, 진 서데나');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '알렉스 보베어드, 린다 빌라로보스, 제니퍼 자이드');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '카르멘 쿠바');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '국수란, 윤종빈, 문용찬');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤종빈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이일형, 윤종빈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '유억');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '배일혁');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '황상준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김상범');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤성기');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김창섭');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '정은영, 유청, 박준용');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이희은, 황효균, 곽태용, 정도안, 조경규, 김대준');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '허명행, 권지훈');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최의영, 박선');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '아담 볼링, 데이빗 레이드, 매튜 본');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '랄프 파인즈, 데이브 기본스, 스티븐 막스, 마크 밀러, 클라우디아 쉬퍼');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '마크 밀러, 데이브 기본스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '매튜 본, 칼 가이두섹');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '벤 데이비스');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '도미닉 루이스, 매튜 마르게슨');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '제이슨 발랜타인, 로버트 홀');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '대런 길포드, 더그 J. 미어딩크, 도미닉 카폰');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '미셀 클랩튼');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '렉 포어스코트-에저튼');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '에탄 코헨, 아론 블라비');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '아론 블라비');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '에탄 코헨, 힐러리 윈스턴');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김주경');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '서규석');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김언수');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '천명관');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '강국현');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김효성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '윤일상');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '김창주');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이재성');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이상민');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '이상하');
INSERT INTO mTBLCREW VALUES (CREW_Seq.nextval, '최의영, 김현정');
DROP SEQUENCE CREW_Seq;